using System.ComponentModel.DataAnnotations;

namespace Pulse.Models
{
    /// <summary>
    /// Represents a pulse question created by an instructor.
    /// Used for both creating and displaying questions.
    /// </summary>
    public class QuestionModel
    {
        /// <summary>
        /// Unique identifier for the question (generated by backend)
        /// </summary>
        public string? Id { get; set; }

        /// <summary>
        /// The question text displayed to students
        /// </summary>
        [Required(ErrorMessage = "Question text is required")]
        [StringLength(500, MinimumLength = 10, 
            ErrorMessage = "Question must be between 10 and 500 characters")]
        public string QuestionText { get; set; } = string.Empty;

        /// <summary>
        /// The type of answer expected: "MCQ" (Multiple Choice) or "FreeText"
        /// </summary>
        [Required(ErrorMessage = "Answer type is required")]
        public AnswerType AnswerType { get; set; } = AnswerType.MCQ;

        /// <summary>
        /// Time limit in seconds for students to answer the question.
        /// Minimum 5 seconds, maximum 600 seconds (10 minutes)
        /// </summary>
        [Required(ErrorMessage = "Timer is required")]
        [Range(5, 600, ErrorMessage = "Timer must be between 5 and 600 seconds")]
        public int TimerSeconds { get; set; } = 30;

        /// <summary>
        /// Indicates whether student responses should be anonymous
        /// </summary>
        public bool IsAnonymous { get; set; } = false;

        /// <summary>
        /// Optional multiple choice options (used when AnswerType is MCQ)
        /// </summary>
        public List<string> MCQOptions { get; set; } = new();

        /// <summary>
        /// Indices of the correct MCQ options (0-based). Used when AnswerType is MCQ
        /// </summary>
        public List<int> CorrectOptionIndices { get; set; } = new();

        /// <summary>
        /// Timestamp when the question was created
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// The ID of the instructor who created this question
        /// </summary>
        public string? InstructorId { get; set; }
    }

    /// <summary>
    /// Enumeration of answer types supported by Pulse
    /// </summary>
    public enum AnswerType
    {
        MCQ = 0,      // Multiple Choice Question
        FreeText = 1  // Free Text Response
    }
}
